services:
  server:
    build: ./server
    container_name: shopper_back
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DATABASE_URL=file:./dev.db
      - PORT=8080

  client:
    build:
      context: ./client
      args:
        VITE_GOOGLE_API_KEY: ${GOOGLE_API_KEY} # Passa a chave para o ARG no Dockerfile
    container_name: shoper_front
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://shopper_back:8080

networks:
  app-network:
    driver: bridge
